version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    restart: always

  py_local:
      build:
        context: ./
        dockerfile: Dockerfile